apiVersion: v1
kind: Service
metadata:
  name: mock-akamai-edge
  labels:
    app: mock-akamai-edge
    ingress.jpmc.com/component: data-plane
spec:
  selector:
    app: mock-akamai-edge
  ports:
    - port: 8011
      targetPort: 8011
      protocol: TCP
  type: ClusterIP
