apiVersion: v1
kind: Service
metadata:
  name: management-api
  labels:
    app: management-api
    ingress.jpmc.com/component: control-plane
spec:
  selector:
    app: management-api
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
  type: ClusterIP
