apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    app: postgres
    ingress.jpmc.com/component: data-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
