apiVersion: v1
kind: Service
metadata:
  name: svc-api
  labels:
    app: svc-api
    ingress.jpmc.com/component: data-plane
spec:
  selector:
    app: svc-api
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
  type: ClusterIP
