import React, { useState, useRef, useCallback, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Sparkles, Play, Pause, RotateCcw, ChevronRight, ChevronLeft, Terminal, FileSearch,
  ListTree, FileCode2, ScanSearch, ShieldCheck, UserCheck, Rocket, PartyPopper, Check, ArrowRight,
} from 'lucide-react'

// ── Content for each step of the pipeline ───────────────────────────────────

const ENDPOINTS = [
  { method: 'POST', path: '/api/v1/users/register', body: 'UserRegistration' },
  { method: 'GET', path: '/api/v1/users/{user_id}', body: null },
  { method: 'GET', path: '/health', body: null },
]

const ROUTE_YAML = `apiVersion: ingress.jpmc.com/v1alpha1
kind: Route
metadata:
  name: users-register
spec:
  path: "/api/v1/users/register"
  hostname: "demo-user-api.jpm.com"
  targetFleet: "demo-user-api"
  backendUrl: "http://host.docker.internal:8123"
  gatewayType: envoy
  authnMechanism: "none"
  methods: [POST]
  notes: >-
    Generated by the repo-onboarding agent from
    UserRegistration (full_name, email, phone, date_of_birth).`

const SCHEMA_FIELDS = [
  { name: 'full_name', type: 'string', format: 'non-empty' },
  { name: 'email', type: 'string', format: 'email' },
  { name: 'phone', type: 'string', format: 'E.164 phone' },
  { name: 'date_of_birth', type: 'string', format: 'YYYY-MM-DD' },
]

const REGO_SNIPPET = `package ingress.policy.payload.route_users_register

default allow = false

required_fields := {"full_name","email","phone","date_of_birth"}

email_valid if {
  is_string(input.body.email)
  regex.match(\`^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$\`, input.body.email)
}
# ...phone_valid, dob_valid, full_name_valid — same pattern

allow if {
  all_required_present
  email_valid; phone_valid; dob_valid; full_name_valid
}`

const DEPLOY_ITEMS = [
  { label: 'Fleet created', detail: 'demo-user-api · xCIB · envoy' },
  { label: 'Routes deployed', detail: '3 routes linked to the fleet' },
  { label: 'Policy attached', detail: 'route_users_register compiled by OPA and attached' },
]

// ── Step definitions ─────────────────────────────────────────────────────────

function StepPrompt() {
  return (
    <div className="rounded-xl p-5 font-mono text-[13px]" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-3 text-[10px] tracking-widest uppercase" style={{ color: '#4a9edd' }}>
        <Terminal size={12} /> Claude Code
      </div>
      <div style={{ color: '#7a8a9a' }}>
        <span style={{ color: '#4ade80' }}>❯</span> /onboard-repo{' '}
        <motion.span
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4, duration: 0.6 }}
          style={{ color: '#e2e8f0' }}
        >
          https://github.com/gavinhamilton1/demo-user-registration-api
        </motion.span>
      </div>
      <motion.div
        initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.1 }}
        className="mt-4 text-[12px]" style={{ color: '#4a9edd' }}
      >
        ⏺ I'll onboard this repo — scanning source for HTTP routes and request-payload schemas…
      </motion.div>
    </div>
  )
}

function StepScan() {
  const files = ['app/main.py', 'app/routes/users.py', 'app/models.py']
  return (
    <div className="rounded-xl p-5" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-4 text-[10px] tracking-widest uppercase" style={{ color: '#4a9edd' }}>
        <ScanSearch size={12} /> Scanning repository
      </div>
      <div className="space-y-2 font-mono text-[12px]">
        {files.map((f, i) => (
          <motion.div
            key={f}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 + i * 0.45 }}
            className="flex items-center gap-2 px-3 py-2 rounded-lg"
            style={{ background: '#0d1420', border: '0.5px solid #1a2a3a' }}
          >
            <FileSearch size={14} className="text-blue-400 shrink-0" />
            <span style={{ color: '#c9d1d9' }}>{f}</span>
            <motion.span
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.7 + i * 0.45 }}
              className="ml-auto"
            >
              <Check size={14} className="text-green-400" />
            </motion.span>
          </motion.div>
        ))}
      </div>
    </div>
  )
}

function StepEndpoints() {
  return (
    <div className="rounded-xl p-5" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-4 text-[10px] tracking-widest uppercase" style={{ color: '#4a9edd' }}>
        <ListTree size={12} /> Endpoints identified
      </div>
      <div className="space-y-1.5">
        {ENDPOINTS.map((e, i) => (
          <motion.div
            key={e.path}
            initial={{ opacity: 0, x: -12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.25 + i * 0.35 }}
            className="flex items-center gap-3 px-3 py-2.5 rounded-lg font-mono text-[12px]"
            style={{ background: '#0d1420', border: '0.5px solid #1a2a3a' }}
          >
            <span
              className="px-1.5 py-0.5 rounded text-[10px] font-bold shrink-0"
              style={{
                background: e.method === 'POST' ? 'rgba(74,158,221,0.15)' : 'rgba(46,204,113,0.15)',
                color: e.method === 'POST' ? '#4a9edd' : '#2ecc71',
              }}
            >
              {e.method}
            </span>
            <span style={{ color: '#c9d1d9' }}>{e.path}</span>
            {e.body && (
              <span className="ml-auto text-[10px]" style={{ color: '#4a5a70' }}>
                body: {e.body}
              </span>
            )}
          </motion.div>
        ))}
      </div>
    </div>
  )
}

function StepYaml() {
  return (
    <div className="rounded-xl p-5" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-3 text-[10px] tracking-widest uppercase" style={{ color: '#4a9edd' }}>
        <FileCode2 size={12} /> Route CRD generated · ingress/routes/users-register.yaml
      </div>
      <motion.pre
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5 }}
        className="font-mono text-[10.5px] leading-relaxed p-3 rounded-lg overflow-x-auto"
        style={{ background: '#080b12', color: '#8ab8e0', border: '0.5px solid #131a28' }}
      >
        {ROUTE_YAML}
      </motion.pre>
    </div>
  )
}

function StepSchema() {
  return (
    <div className="rounded-xl p-5" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-4 text-[10px] tracking-widest uppercase" style={{ color: '#4a9edd' }}>
        <ScanSearch size={12} /> Payload schema scanned · UserRegistration
      </div>
      <div className="grid grid-cols-2 gap-2">
        {SCHEMA_FIELDS.map((f, i) => (
          <motion.div
            key={f.name}
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.2 + i * 0.25 }}
            className="rounded-lg px-3 py-2.5"
            style={{ background: '#0d1420', border: '0.5px solid #1a2a3a' }}
          >
            <div className="font-mono text-[12px]" style={{ color: '#c9d1d9' }}>{f.name}</div>
            <div className="text-[10px] mt-0.5" style={{ color: '#4a9edd' }}>{f.format}</div>
          </motion.div>
        ))}
      </div>
    </div>
  )
}

function StepRego() {
  return (
    <div className="rounded-xl p-5" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-3 text-[10px] tracking-widest uppercase" style={{ color: '#4a9edd' }}>
        <ShieldCheck size={12} /> OPA policy generated · ingress/policies/route_users_register.rego
      </div>
      <motion.pre
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5 }}
        className="font-mono text-[10.5px] leading-relaxed p-3 rounded-lg overflow-x-auto"
        style={{ background: '#080b12', color: '#8ac8a0', border: '0.5px solid #131a28' }}
      >
        {REGO_SNIPPET}
      </motion.pre>
      <div className="mt-2 text-[10.5px]" style={{ color: '#4a5a70' }}>
        No SQLi/XSS checks here — that's the platform-wide global policy's job. This policy only knows this route's own schema.
      </div>
    </div>
  )
}

function StepReview() {
  return (
    <div className="rounded-xl p-5 flex flex-col items-center text-center" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-4 text-[10px] tracking-widest uppercase self-start" style={{ color: '#4a9edd' }}>
        <UserCheck size={12} /> Developer review gate
      </div>
      <p className="text-[12px] max-w-md mb-4" style={{ color: '#8aa8c8' }}>
        "Ready to register this against the live platform? This will create the route and attach the policy."
      </p>
      <motion.div
        initial={{ scale: 0, rotate: -15, opacity: 0 }}
        animate={{ scale: 1, rotate: -8, opacity: 1 }}
        transition={{ delay: 0.6, type: 'spring', stiffness: 260, damping: 14 }}
        className="px-5 py-2 rounded-lg font-bold text-sm tracking-wide"
        style={{ background: 'rgba(46,204,113,0.12)', border: '2px solid #2ecc71', color: '#2ecc71' }}
      >
        ✓ APPROVED
      </motion.div>
    </div>
  )
}

function StepDeploy() {
  return (
    <div className="rounded-xl p-5" style={{ background: '#0a0e1a', border: '0.5px solid #1a2a3a' }}>
      <div className="flex items-center gap-2 mb-4 text-[10px] tracking-widest uppercase" style={{ color: '#4a9edd' }}>
        <Rocket size={12} /> Deploying to the ingress platform
      </div>
      <div className="space-y-2">
        {DEPLOY_ITEMS.map((item, i) => (
          <motion.div
            key={item.label}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 + i * 0.6 }}
            className="flex items-center gap-3 px-3 py-2.5 rounded-lg"
            style={{ background: '#0d1420', border: '0.5px solid #1a2a3a' }}
          >
            <motion.div
              initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ delay: 0.6 + i * 0.6, type: 'spring' }}
              className="w-5 h-5 rounded-full flex items-center justify-center shrink-0"
              style={{ background: 'rgba(46,204,113,0.15)' }}
            >
              <Check size={12} className="text-green-400" />
            </motion.div>
            <div>
              <div className="text-[12px] font-semibold" style={{ color: '#e2e8f0' }}>{item.label}</div>
              <div className="text-[10px]" style={{ color: '#4a5a70' }}>{item.detail}</div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  )
}

function StepLive() {
  return (
    <div className="rounded-xl p-6 flex flex-col items-center text-center" style={{ background: 'linear-gradient(180deg, rgba(46,204,113,0.06), transparent)', border: '0.5px solid #1a3a2a' }}>
      <motion.div
        initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: 'spring', stiffness: 200 }}
        className="w-14 h-14 rounded-full flex items-center justify-center mb-3"
        style={{ background: 'rgba(46,204,113,0.15)' }}
      >
        <PartyPopper size={26} className="text-green-400" />
      </motion.div>
      <div className="text-lg font-bold text-white mb-1">Live at demo-user-api.jpm.com</div>
      <p className="text-[12px] mb-4 max-w-sm" style={{ color: '#8aa8c8' }}>
        Visible in the Console's Fleets &amp; Routes pages, enforced by envoy-control-plane and auth-service within seconds — no developer ever hand-wrote a Route CRD or a Rego policy.
      </p>
      <Link
        to="/traffic-flow"
        className="flex items-center gap-1.5 text-xs px-4 py-2 rounded-lg font-semibold"
        style={{ background: 'rgba(74,158,221,0.15)', color: '#4a9edd', border: '0.5px solid #1a4a7a' }}
      >
        See it handle real traffic <ArrowRight size={14} />
      </Link>
    </div>
  )
}

const STEPS = [
  { id: 'prompt', label: 'Prompt', render: StepPrompt, hold: 2600 },
  { id: 'scan', label: 'Scan repo', render: StepScan, hold: 2600 },
  { id: 'endpoints', label: 'Find endpoints', render: StepEndpoints, hold: 2600 },
  { id: 'yaml', label: 'Generate Route CRD', render: StepYaml, hold: 3200 },
  { id: 'schema', label: 'Scan payload schema', render: StepSchema, hold: 2600 },
  { id: 'rego', label: 'Generate OPA policy', render: StepRego, hold: 3400 },
  { id: 'review', label: 'Developer review', render: StepReview, hold: 2600 },
  { id: 'deploy', label: 'Deploy to platform', render: StepDeploy, hold: 3400 },
  { id: 'live', label: 'Live', render: StepLive, hold: 999999 },
]

// ── Main page ─────────────────────────────────────────────────────────────────

export default function OnboardingFlow() {
  const [current, setCurrent] = useState(0)
  const [playing, setPlaying] = useState(false)
  const cancelRef = useRef(false)

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

  const play = useCallback(async () => {
    cancelRef.current = false
    setPlaying(true)
    let i = current >= STEPS.length - 1 ? 0 : current
    setCurrent(i)
    while (i < STEPS.length - 1) {
      await sleep(STEPS[i].hold)
      if (cancelRef.current) return
      i += 1
      setCurrent(i)
    }
    setPlaying(false)
  }, [current])

  useEffect(() => () => { cancelRef.current = true }, [])

  const stop = () => { cancelRef.current = true; setPlaying(false) }
  const restart = () => { cancelRef.current = true; setPlaying(false); setCurrent(0) }
  const next = () => { cancelRef.current = true; setPlaying(false); setCurrent((c) => Math.min(c + 1, STEPS.length - 1)) }
  const prev = () => { cancelRef.current = true; setPlaying(false); setCurrent((c) => Math.max(c - 1, 0)) }

  const Active = STEPS[current].render

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between mb-2">
        <div>
          <h1 className="text-xl font-bold text-white flex items-center gap-2">
            <Sparkles size={20} className="text-blue-400" />
            Repo Onboarding, Automated
          </h1>
          <p className="text-sm text-jpmc-muted">
            From a raw GitHub URL to a live, policy-protected route — no developer hand-writes YAML or Rego.
          </p>
        </div>
        <div className="flex items-center gap-2">
          {playing ? (
            <button onClick={stop} className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded font-mono font-semibold" style={{ background: '#2a0a0a', border: '0.5px solid #7a1a1a', color: '#e74c3c' }}>
              <Pause size={12} /> Pause
            </button>
          ) : (
            <button onClick={play} className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded font-mono font-semibold" style={{ background: '#0a1a2a', border: '0.5px solid #1a4a7a', color: '#4a9edd' }}>
              <Play size={12} /> Play
            </button>
          )}
          <button onClick={restart} className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded font-mono font-semibold" style={{ background: '#0a0a14', border: '0.5px solid #1a2a3a', color: '#7a8a9a' }}>
            <RotateCcw size={12} /> Restart
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-4">
        {/* Step rail */}
        <div className="rounded-xl p-3 space-y-1" style={{ background: '#0d1117', border: '0.5px solid #1a1a2a' }}>
          {STEPS.map((s, i) => (
            <button
              key={s.id}
              onClick={() => { cancelRef.current = true; setPlaying(false); setCurrent(i) }}
              className="w-full flex items-center gap-2.5 px-2.5 py-2 rounded-lg text-left transition-colors"
              style={{
                background: i === current ? 'rgba(74,158,221,0.12)' : 'transparent',
                color: i === current ? '#4a9edd' : i < current ? '#4a5a70' : '#3a4a5a',
              }}
            >
              <div
                className="w-5 h-5 rounded-full flex items-center justify-center text-[9px] font-bold shrink-0"
                style={{
                  background: i < current ? 'rgba(46,204,113,0.15)' : i === current ? 'rgba(74,158,221,0.2)' : '#131a28',
                  color: i < current ? '#2ecc71' : i === current ? '#4a9edd' : '#3a4a5a',
                }}
              >
                {i < current ? <Check size={11} /> : i + 1}
              </div>
              <span className="text-[11.5px] font-medium">{s.label}</span>
            </button>
          ))}
        </div>

        {/* Active step panel */}
        <div>
          <AnimatePresence mode="wait">
            <motion.div
              key={STEPS[current].id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
            >
              <Active />
            </motion.div>
          </AnimatePresence>

          <div className="flex items-center justify-between mt-3">
            <button
              onClick={prev}
              disabled={current === 0}
              className="flex items-center gap-1 text-xs px-3 py-1.5 rounded font-mono disabled:opacity-30"
              style={{ background: '#0a0a14', border: '0.5px solid #1a2a3a', color: '#7a8a9a' }}
            >
              <ChevronLeft size={13} /> Back
            </button>
            <div className="text-[10px] font-mono" style={{ color: '#3a4a5a' }}>
              STEP {current + 1} / {STEPS.length}
            </div>
            <button
              onClick={next}
              disabled={current === STEPS.length - 1}
              className="flex items-center gap-1 text-xs px-3 py-1.5 rounded font-mono disabled:opacity-30"
              style={{ background: '#0a0a14', border: '0.5px solid #1a2a3a', color: '#7a8a9a' }}
            >
              Next <ChevronRight size={13} />
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
