import React from 'react'
import { motion } from 'framer-motion'
import {
  ShieldHalf, Monitor, Cloud, Radio, Route as RouteIcon, ShieldCheck, Server,
  Lock, Globe2, ScanEye, Bot, KeyRound, Fingerprint, ListChecks, Regex, Braces, Code2, Ban,
  Building2, CloudCog, ShieldAlert,
} from 'lucide-react'

// ── Data: hops nested under their real network tier ─────────────────────────
// Tier 1/2/3 here are JPM's own network zones — not the policy layers.
// PSaaS/AWS WAF is Tier 1 (perimeter). The gateways AND both policy checks
// all live inside Tier 2 — that's the trust boundary: nothing enters Tier 3
// (the trusted backend network) without clearing every check in Tier 2.
// Client/GTM/CDN sit in front of all of it, on the public internet.
//
// Hop colors match TrafficFlow.jsx's stage palette so the two pages read as
// one system.

const TIER_GROUPS = [
  {
    id: 'external',
    label: 'PUBLIC INTERNET',
    desc: 'Outside JPM-owned infrastructure — third-party CDN/DNS providers',
    color: '#5a6a7a',
    tlsAfter: 'TLS TERMINATES HERE',
    hops: [
      {
        icon: Monitor, color: '#7a8a9a', bg: 'rgba(122,138,154,0.06)', border: '#2a3a4a',
        title: 'Client', tech: 'Browser · curl · mobile app',
        protections: [
          { icon: Lock, text: 'TLS 1.2+ required end to end' },
        ],
      },
      {
        icon: Globe2, color: '#c8a020', bg: 'rgba(200,160,32,0.06)', border: '#3a3010',
        title: 'Global Traffic Management', tech: 'Akamai GTM · Cloudflare LB',
        protections: [
          { icon: Globe2, text: 'GeoDNS — nearest healthy datacenter' },
          { icon: ScanEye, text: 'Active health checks — automatic failover' },
        ],
      },
      {
        icon: Cloud, color: '#e67e22', bg: 'rgba(230,126,34,0.06)', border: '#3a2010',
        title: 'CDN Edge', tech: 'Akamai Edge · Cloudflare Edge',
        protections: [
          { icon: Lock, text: 'TLS termination — outer TLS boundary' },
          { icon: Bot, text: 'Bot detection — missing/suspicious User-Agent' },
          { icon: ShieldHalf, text: 'WAF rules — XSS & path-traversal patterns in path/query' },
        ],
      },
    ],
  },
  {
    id: 'tier1',
    label: 'TIER 1 — PERIMETER',
    desc: 'Two parallel paths, chosen by where the workload is hosted — both terminate the same way into Tier 2',
    color: '#d35400',
    layout: 'parallel',
    tlsAfter: 'TLS RE-ORIGINATED',
    hops: [
      {
        icon: Building2, color: '#d35400', bg: 'rgba(211,84,0,0.06)', border: '#3a2a10',
        title: 'PSaaS+', tech: 'On-prem / private datacenters',
        protections: [
          { icon: ShieldAlert, text: 'WAF ruleset — SQLi / XSS / OWASP Top 10 patterns' },
          { icon: Lock, text: 'TLS re-origination — inner TLS boundary' },
        ],
      },
      {
        icon: CloudCog, color: '#e08030', bg: 'rgba(224,128,48,0.06)', border: '#3a2a10',
        title: 'AWS WAF', tech: 'AWS-hosted workloads',
        protections: [
          { icon: ShieldAlert, text: 'AWS WAF managed rule groups — SQLi / XSS / bad-bot' },
          { icon: Lock, text: 'TLS re-origination — inner TLS boundary' },
        ],
      },
    ],
  },
  {
    id: 'tier2',
    label: 'TIER 2 — GATEWAY',
    desc: 'The trust boundary — gateway + every policy check live here. Nothing reaches Tier 3 without clearing all of it.',
    color: '#4a9edd',
    hops: [
      {
        icon: RouteIcon, color: '#4a9edd', bg: 'rgba(74,158,221,0.06)', border: '#0a2040',
        title: 'Gateway', tech: 'gateway-envoy · gateway-kong',
        protections: [
          { icon: Regex, text: 'Route matching — exact & templated ({param}) paths' },
          { icon: KeyRound, text: 'ext_authz — every request checked before the backend is touched' },
        ],
      },
      {
        icon: ShieldCheck, color: '#22d3ee', bg: 'rgba(34,211,238,0.07)', border: '#0a3a4a',
        title: 'Global Policy', tech: 'auth-service · OPA · ingress.policy.payload.global',
        protections: [
          { icon: Fingerprint, text: 'JWT / DPoP session validation (bearer routes)' },
          { icon: Code2, text: 'Generic injection-pattern detection — SQLi, XSS, NoSQL' },
          { icon: ShieldHalf, text: 'Runs against every route platform-wide, before Route Policy' },
        ],
      },
      {
        icon: ShieldCheck, color: '#2ecc71', bg: 'rgba(46,204,113,0.07)', border: '#1a3a2a',
        title: 'Route Policy', tech: 'auth-service · OPA · route-specific package',
        protections: [
          { icon: ListChecks, text: 'Required-field presence — from the route’s own schema' },
          { icon: Braces, text: 'Format checks — email / phone / date, per field' },
          { icon: ShieldCheck, text: 'Generated by the onboarding skill, unique per route' },
        ],
      },
    ],
  },
  {
    id: 'tier3',
    label: 'TIER 3 — TRUSTED INTERNAL',
    desc: 'Your backend network — reachable only by traffic Tier 2 has already cleared',
    color: '#2ecc71',
    hops: [
      {
        icon: Server, color: '#94a3b8', bg: 'rgba(148,163,184,0.06)', border: '#2a3042',
        title: 'Backend', tech: 'the onboarded service itself',
        protections: [
          { icon: Code2, text: 'Framework-level validation — Pydantic / Joi / etc.' },
          { icon: ListChecks, text: 'Business logic — the only layer that knows the domain' },
        ],
      },
    ],
  },
]

// ── Small building blocks ────────────────────────────────────────────────────

function TLSMarker({ label }) {
  return (
    <div className="flex items-center gap-3 my-1 pl-16">
      <div className="flex-1 h-px" style={{ background: 'linear-gradient(90deg, #0e6a6a, transparent)' }} />
      <div
        className="text-[9px] font-bold tracking-wider whitespace-nowrap font-mono px-3 py-1 rounded-md"
        style={{ color: '#0e9a9a', border: '0.5px solid #0e6a6a', background: 'rgba(0,0,0,0.3)' }}
      >
        {label}
      </div>
      <div className="flex-1 h-px" style={{ background: 'linear-gradient(270deg, #0e6a6a, transparent)' }} />
    </div>
  )
}

function HopBlock({ hop, isLast, showConnector = true }) {
  const Icon = hop.icon
  return (
    <div className="rounded-xl p-4 flex gap-4 h-full" style={{ background: hop.bg, border: `0.5px solid ${hop.border}` }}>
      {/* Icon + connecting line */}
      <div className="flex flex-col items-center shrink-0">
        <div
          className="w-11 h-11 rounded-2xl flex items-center justify-center"
          style={{ background: '#0a0e1a', border: `1.5px solid ${hop.color}`, boxShadow: `0 0 14px ${hop.color}33` }}
        >
          <Icon size={20} style={{ color: hop.color }} />
        </div>
        {showConnector && !isLast && (
          <div className="w-px flex-1 mt-2" style={{ background: `linear-gradient(180deg, ${hop.color}55, transparent)`, minHeight: 12 }} />
        )}
      </div>

      {/* Content */}
      <div className="flex-1 min-w-0 pb-1">
        <div className="flex items-baseline gap-2 flex-wrap">
          <span className="text-[13px] font-bold" style={{ color: hop.color }}>{hop.title}</span>
          <span className="text-[10px] font-mono" style={{ color: '#4a5a70' }}>{hop.tech}</span>
        </div>
        <div className="mt-2 grid sm:grid-cols-2 gap-1.5">
          {hop.protections.map((p, i) => {
            const PIcon = p.icon
            return (
              <div
                key={i}
                className="flex items-start gap-1.5 text-[10.5px] leading-snug px-2 py-1.5 rounded-lg"
                style={{ background: 'rgba(255,255,255,0.02)', color: '#b0c0d0' }}
              >
                <PIcon size={12} className="shrink-0 mt-0.5" style={{ color: hop.color }} />
                <span>{p.text}</span>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

function TierBand({ group, groupIndex, isExternal }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-60px' }}
      transition={{ duration: 0.4, delay: Math.min(groupIndex * 0.1, 0.3) }}
      className="rounded-2xl p-4"
      style={{
        background: isExternal ? 'transparent' : `${group.color}0d`,
        border: isExternal ? '0.5px dashed #2a3042' : `1px solid ${group.color}40`,
      }}
    >
      <div className="flex items-baseline gap-2 mb-3 px-1 flex-wrap">
        <span
          className="text-[11px] font-bold tracking-[0.12em] font-mono px-2 py-0.5 rounded"
          style={{ color: isExternal ? '#7a8a9a' : group.color, background: isExternal ? 'rgba(122,138,154,0.1)' : `${group.color}1a` }}
        >
          {group.label}
        </span>
        <span className="text-[10.5px]" style={{ color: '#5a6a7a' }}>{group.desc}</span>
      </div>
      {group.layout === 'parallel' ? (
        <div className="grid sm:grid-cols-2 gap-3 relative">
          {group.hops.map((hop) => (
            <HopBlock key={hop.title} hop={hop} showConnector={false} />
          ))}
          <div
            className="hidden sm:flex absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 items-center justify-center w-8 h-8 rounded-full text-[9px] font-bold z-10"
            style={{ background: '#0a0e1a', border: `1.5px solid ${group.color}`, color: group.color }}
          >
            OR
          </div>
        </div>
      ) : (
        <div className="space-y-2">
          {group.hops.map((hop, i) => (
            <HopBlock key={hop.title} hop={hop} isLast={i === group.hops.length - 1} />
          ))}
        </div>
      )}
      {group.tlsAfter && <TLSMarker label={group.tlsAfter} />}
    </motion.div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function ProtectionArchitecture() {
  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-xl font-bold text-white flex items-center gap-2">
          <ShieldHalf size={20} className="text-blue-400" />
          Protection at Every Hop
        </h1>
        <p className="text-sm text-jpmc-muted">
          Defense in depth across three network tiers — Tier 2 is the trust boundary that decides what's allowed into Tier 3.
        </p>
      </div>

      <div className="space-y-3">
        {TIER_GROUPS.map((group, i) => (
          <TierBand key={group.id} group={group} groupIndex={i} isExternal={group.id === 'external'} />
        ))}
      </div>

      {/* Tier 2 = trust boundary callout */}
      <div className="rounded-lg p-4 flex items-start gap-3" style={{ background: 'rgba(74,158,221,0.06)', border: '0.5px solid #1a3a5a' }}>
        <Ban size={18} className="text-blue-400 shrink-0 mt-0.5" />
        <div className="text-[11px] leading-relaxed" style={{ color: '#8aa8c8' }}>
          <strong style={{ color: '#4a9edd' }}>Tier 2 is the only gate.</strong> The gateway, the global injection-pattern policy,
          and the route-specific schema policy all run here — a request has to clear every one of them before it can reach
          Tier 3. Tier 3 never has to trust the network; it only ever sees traffic Tier 2 already vetted.
        </div>
      </div>

      {/* Why two policy checks — callout */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <div className="rounded-lg p-4" style={{ background: 'rgba(34,211,238,0.05)', border: '0.5px solid #0a3a4a' }}>
          <div className="text-[11px] font-bold tracking-wide mb-1.5" style={{ color: '#22d3ee' }}>WHY A GLOBAL CHECK EXISTS</div>
          <div className="text-[11px] leading-relaxed" style={{ color: '#8ab8c8' }}>
            A newly discovered attack pattern gets blocked platform-wide with <strong>one policy update</strong> —
            no need to regenerate or reattach every individual route's own policy.
          </div>
        </div>
        <div className="rounded-lg p-4" style={{ background: 'rgba(46,204,113,0.05)', border: '0.5px solid #1a3a2a' }}>
          <div className="text-[11px] font-bold tracking-wide mb-1.5" style={{ color: '#2ecc71' }}>WHY A ROUTE CHECK EXISTS</div>
          <div className="text-[11px] leading-relaxed" style={{ color: '#8ac8a0' }}>
            Only the route's own developer (or the onboarding skill, scanning their schema) knows which fields are
            required and what a valid email/phone/date looks like for that specific endpoint.
          </div>
        </div>
      </div>
    </div>
  )
}
