apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
    ingress.jpmc.com/component: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
        ingress.jpmc.com/component: control-plane
    spec:
      containers:
        - name: console
          image: ingress-poc/console:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 100m
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: console-nginx-config
