apiVersion: v1
kind: Service
metadata:
  name: watchdog
  labels:
    app: watchdog
    ingress.jpmc.com/component: control-plane
spec:
  selector:
    app: watchdog
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
  type: ClusterIP
