apiVersion: v1
kind: Service
metadata:
  name: gateway-kong
  labels:
    app: gateway-kong
    ingress.jpmc.com/component: data-plane
spec:
  selector:
    app: gateway-kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
