apiVersion: v1
kind: Service
metadata:
  name: dns
  labels:
    app: dns
    ingress.jpmc.com/component: control-plane
spec:
  selector:
    app: dns
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  type: ClusterIP
