apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-cp

resources:
  - namespace.yaml
  - postgres
  - jaeger
  - auth-service
  - opa
  - management-api
  - envoy-control-plane
  - gateway-envoy
  - gateway-kong
  - kong-admin-proxy
  - mock-akamai-gtm
  - mock-akamai-edge
  - mock-psaas
  - svc-web
  - svc-api
  - console
  - watchdog
  - dns
  - ingress-operator
