apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
    ingress.jpmc.com/component: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
        ingress.jpmc.com/component: control-plane
    spec:
      containers:
        - name: opa
          image: ingress-poc/opa:latest
          ports:
            - containerPort: 8181
              protocol: TCP
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 100m
